version: "2"

services:
  web:
    image: "nginx:latest"
    working_dir: /app
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 8003:80
    links:
      - php
  php:
    build: "."
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - ./development.env
    links:
      - mysqldb
  mysqldb:
    image: "mysql:latest"
    ports:
      - 3308:3306
    env_file:
      - ./development.env
